# Generated by Django 2.2.1 on 2019-05-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20190523_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldType', to='risk.FieldType'),
        ),
    ]
