# Generated by Django 2.2.1 on 2019-05-24 11:22

from django.db import migrations


def populate_field_type_table(apps, schema_editor):
    FieldType = apps.get_model('risk', 'FieldType')
    FieldType.objects.create(name="text")
    FieldType.objects.create(name="date")
    FieldType.objects.create(name="number")
    FieldType.objects.create(name="currency")
    FieldType.objects.create(name="enum")


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_enumvalues'),
    ]

    operations = [
        migrations.RunPython(populate_field_type_table)
    ]
